# This is the configuration used to check the source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/dummy/**/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
